micronaut:
  application:
    name: micronaut-cache-example
---
#Datasource
hibernate:
  hbm2ddl:
    auto: update
dataSource:
  logSql: true
  driverClassName: org.h2.Driver
  username: sa
  password: ''
  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
---
